name: Publish to PyPI

on:
  release:
    branches:
     - main
    types: [published]

jobs:
  PyPI-Release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      with:
        path: main
    - name: Build Package
      run: |
        python3 -m pip install --upgrade pip build
        python3 -m build
    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TESTPYPI_API_TOKEN }}
        repository_url: http://test.pypi.org/legacy/
